# Generated by Django 3.2.3 on 2024-12-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('gender', models.IntegerField(choices=[(1, 'Man'), (2, 'Woman')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pname', models.CharField(db_column='publisher_name', max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.TextField(max_length=512)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
    ]
