"""
Django settings for a_django_basic project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 项目根目录的绝对路径, __file__是当前文件.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 每个django的key标志.
SECRET_KEY = 'django-insecure-@33=+r149v54-b^z!3%@6p%%ta1+6m@$wa=+v459@ac%@82yqx'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG: 调试模式. 一旦项目报错, 错误信息显示在前端页面.
# 开发过程中使用True方便观察错误信息调试, 项目上线改为False.
# 当配置为False时, 需要配置ALLOWED_HOSTS.
DEBUG = True

# 允许浏览器通过哪些域名或IP访问我的网站.
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
#    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 浏览器请求先访问哪个路由配置文件
ROOT_URLCONF = 'a_django_basic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 配置生产WSGI生产环境服务时查找的文件
WSGI_APPLICATION = 'a_django_basic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# 默认语言: en-us 英语; zh-Hans 汉语
LANGUAGE_CODE = 'zh-Hans'

# 时区: Asia/Shanghai
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

# 本地化翻译, 一般默认, 不怎么用
USE_I18N = True

# 数据本地格式化, 一般默认, 不怎么用
USE_L10N = True

# 是否使用感知时间
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

# 默认自动字段. 自动添加主键, 主键默认为BigInt, 自动增长
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 带有特定含义的, 项目全局的变量也可以在这里设置.
# 项目中每个地方都能导入.
README = "BrianDingDing"
